name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      BOOST_ROOT: ${{github.workspace}}/boost_1_72_0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Boost
        run: curl -L https://archives.boost.io/release/1.72.0/source/boost_1_72_0.tar.gz | tar zx
        shell: bash
      - name: configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
      - name: configure xetra
        run: cmake -B ${{github.workspace}}/build-xetra -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DXETRA_FAST_SPECIFICATION=ON
      - name: build
        run: cmake --build ${{github.workspace}}/build --parallel 2
      - name: build xetra
        run: cmake --build ${{github.workspace}}/build-xetra --parallel 2
      - name: test
        run: cd ${{github.workspace}}/build && ctest -VV
      - name: test xetra
        run: cd ${{github.workspace}}/build-xetra && ctest -VV
